export const GET_TODO_REQUESTED = "GET_TODO_REQUESTED";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";
export const ADD_TODO_REQUESTED = "ADD_TODO_REQUESTED";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";
